name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Download module dependencies
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -coverprofile=coverage.txt ./...

      - name: Upload Coverage
        uses: codecov/codecov-action@v3.1.0
        continue-on-error: true
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
          fail_ci_if_error: false
  lint:
    name: "Run static analysis"
    runs-on: ubuntu-latest
    steps:
      - uses: WillAbides/setup-go-faster@v1.5.0
        with:
          go-version: 1.17
      - run: "GO111MODULE=on go get honnef.co/go/tools/cmd/staticcheck"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/staticcheck
          key: staticcheck-${{ github.sha }}
          restore-keys: |
            staticcheck-
      - run: "go vet ./..."
      - run: "$(go env GOPATH)/bin/staticcheck -go 1.17 ./..."